import './globals.css'; 
import { raleway } from './fonts'; 

export const metadata = { 
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className={`${raleway.className} ${raleway.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}