// app/layout.js
import './globals.css'; // Твой глобальный CSS
import { raleway } from './fonts'; // Импорт нашего шрифта

export const metadata = { // Опционально: если у тебя есть metadata
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // ВАЖНО: НЕТ ТЕГА <head> ЗДЕСЬ!
    <html lang="ru" className={`${raleway.className} ${raleway.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}